spring.application.name=Springsec

#spring.security.user.name = __
#spring.security.user.password= __

spring.datasource.url= url 
spring.datasource.username=******
spring.datasource.password=******
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.servlet.session.cookie.same-site=strict
management.endpoint.health.show-details=always
